package com.chronelab.roomdatabase.roomdatabase.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// Represents an item entity in the database
@Entity(tableName = "items")
data class Item(
    // Unique identifier for the item, auto-generated by Room
    @PrimaryKey(autoGenerate = true) val id: Int,

    // Name of the item
    val name: String,

    // Price of the item
    val price: Double,

    // Quantity of the item available
    val quantity: Int
)
